[package]
name = "zerp"
version = "0.1.0"
edition = "2021"


[workspace]
members = [ "crates/*" ]


[workspace.dependencies]
actix-web = { version = "4.8.0" }
auto_ops = { version = "0.3.0" }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }


[dependencies]
actix-web.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

zp_core = { path = "./crates/zp_core" }
zp_service = { path = "./crates/zp_service" }